### ISSUE TITLE
import error on ubuntu14.02

### ISSUE THREAD

**Issue by clf35** [graycatlabs/PyBBIO#53]
Hi i installed pybbio for ubuntu trusty end i checked blink.py but got an error like

ubuntu@arm:/usr/local/lib/PyBBIO/examples$ sudo python blink.py
Traceback (most recent call last):
  File "blink.py", line 7, in <module>
    from bbio import *
  File "/usr/local/lib/python2.7/dist-packages/bbio/__init__.py", line 5, in <module>
    from .bbio import run, stop
  File "/usr/local/lib/python2.7/dist-packages/bbio/bbio.py", line 10, in <module>
    from .platform import platform_init, platform_cleanup
  File "/usr/local/lib/python2.7/dist-packages/bbio/platform/__init__.py", line 5, in <module>
    from beaglebone import *
  File "/usr/local/lib/python2.7/dist-packages/bbio/platform/beaglebone/__init__.py", line 7, in <module>
    from bone_3_8 import config
  File "/usr/local/lib/python2.7/dist-packages/bbio/platform/beaglebone/bone_3_8/config.py", line 20, in <module>
    SLOTS_FILE = glob.glob('/sys/devices/bone_capemgr.*/slots')[0]
IndexError: list index out of range

how can i solve it
regards
Fahri

**Comment by quanpower** [comment]
I have the same problem too,has it be solved?Or how to install capemgr driver on ubuntu 14.04 with 3.14 kernel?

**Comment by clf35** [comment]
İf you find a sd card with kernel 3.8 you can clone it using "ddrescue" command or try to embed terminal command in python. Maybe, it can be a solution for now

**Comment by alexanderhiam** [comment]
Closing this, see issue #63
